### PR TITLE
CHAL-13 #done Refactor /progress

### PR DESCRIPTION
**Pull request by jyyhuang**
## Checklist

> Please ensure you have followed all of the steps below before submitting a pull request:

- [x] Include the corresponding Jira issue key and #done in the PR title, like so: "JRA-123 #done Migrate Election Reminders"
- [x] Verify that the code compiles
- [x] Verify that all tests pass
- [x] Verify that unit tests cover 100% of the code
- [x] Create Storybook stories for visual components
- [x] Verify that any visual components match the Figma
- [x] Test with a screen reader (if applicable)
- [x] Document your code with TSDoc comments
- [x] Format your code with Prettier

## Overview

This PR moves the logic out of the original /progress page into hooks and components. I have also added a mock restartChallenge function to UserService and added a npm package, jest-canvas-mock, for react confetti.

## Test Plan

I have created unit tests for my hooks and components, and also created storybook stories to ensure my components are as intended. I also created snapshot tests for the progress page and badges.

## Follow ups

Inside the progress page, there are several dependencies that have not been implemented yet. These are couponData, partnersExist, and the Invite component. I have commented them as TODO.

### CODE REVIEW

**Comment by jyyhuang** [comment]
There were some errors when npm ci was running, which had to do with canvas npm package, which made me change packages.

**Review by dvorakjt — COMMENTED** [review]
Hi Joey,

This is excellent, overall. I've noticed a few small things, but it shouldn't be much. I need to run the Storybook stories, dev server and tests locally and I then I'll be able to complete my review. Should be done today.

Thank you!

**Review by dvorakjt — CHANGES_REQUESTED** [review]
Great work on this PR. The code is well-organized and thoroughly thought out. This type of clean code helps to greatly improve maintainability and readability.

I have a few suggestions that I think can improve this PR a bit. Thanks in advance for considering them and working to implement them:

1. Please update the badges component so that it doesn't mutate the badges array directly. Because the component receives a reference to an array, the same array maintained within the user object will be mutated. We want to avoid directly mutating a React state variable such as this in order to avoid subtle, hard-to-find bugs. Instead you could use the slice method like this:
<pre>
    export function Badges({ badges = [] }: BadgesProps): JSX.Element {
      badges = badges.slice(0, 8);

      while (badges.length < 8) {
        badges.push({}); //might be better to use null here, please see my next comment
      }
      // rest of your code
 </pre>
 2. Note that the empty object passed into `badges.push` is not technically of the correct type as it lacks the required properties of Badge. I did my best to define types with all of the project requirements in mind, but that being said, there will always be room to refine things, even these types. In this case, I think we can split "Badge" into the two types of badges it can possibly render. Badge could then be a type union of these two types and the badges array could be an array of type Badge | null. Then, the Badge component can be split into three separate components that render each type of badge. You can then move the logic that selects which type of Badge component to render into Badges. You can first perform a check to see if the badge is null, and in that case render the type of badge that presents just the badge number. Then, if the badge is not null, the code that performs these checks in the Badge component (lines 32 - 42) can be extracted out into [type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) and these can be called to determine which of the other two badge types to render. This will simplify the code inside the Badge itself, and make it clearer to the reader what is happening when Badges is rendered. Please let me know if this makes sense, it's a lot to describe, but hopefully I've communicated it clearly.
 
 3. In general, please check that the types that you declare your variables to be correspond exactly to the types of values you've assigned to them. There are a couple cases where variables are declared to be of a certain type (e.g. User) but lack some required properties of that type.
 
 4. The functions you've defined inside hooks are excellent, but they are not technically hooks as they don't involve any features of React. These are more accurately described as utils. One way to handle it would be to create a folder in src called utils and move them there. They could also live closer to your components since they are pretty specific to that context and probably won't see use elsewhere in the application. If they do, we can always move them higher up the tree at that point. Also, to avoid confusion, let's rename `useDaysRemaining` to `calculateDaysRemaining` since the `use` prefix should be reserved for true hooks. The type predicates you define for Badge could also probably live in the folder you create for these functions.

There are also a few small nits:
1. I appreciate your commitment to the TSDoc spec, but I think for our purposes, we should limit the application of this spec to instances where we want to provide extra context about our code. If the code speaks really clearly already, the comments are redundant. I like most of your TSDoc comments, they're really good. I'd just remove the ones that simply restate what the code already says
2. Please use camelCase for images for consistency with style guide 
3.  Line 19 of challenge button, change "curent" to "current"

Great work, looking forward to these updates!

**Comment by jyyhuang** [comment]
I added the necessary changes, and as for the badges, I added an action-badge and player-badge as types and split my component into three parts. I think this is what you were aiming for, but please let me know if i'm wrong!

**Review by dvorakjt — CHANGES_REQUESTED** [review]
Great work! Splitting the badge component up into discrete components for each badge type and leveraging type predicates the way you did makes for extremely clean, easy-to-read and easy-to-change code. Also, thank you for going above and beyond by revising your previous work to conform to the style guide. 

There is one thing I caught, which is important to change. In `challenge-button.test.tsx,` the tests are producing false positives. You can observe this happening if you comment out line 46. This is because the variables you initialized at the top of the describe block are initialized only once for the whole test suite. You can get around this by declaring them without initializing them, and then initializing them inside a beforeEach callback. If you do this and leave the aforementioned line commented out, you should see the test fail. When you uncomment the line, it will pass. Here's an example:

<pre>
describe('ChallengeComplete', () => {
  let toggleInvite: RefObject<() => null>;
  let restartChallenge: () => null;
  let setOpenModal: Dispatch&lt;SetStateAction&lt;boolean&gt;&gt;;

  beforeEach(() => {
    toggleInvite = { current: jest.fn() };
    restartChallenge = jest.fn();
    setOpenModal = jest.fn();
  });

  afterEach(cleanup);

  // rest of your tests...
</pre>

One other thing to consider: could the delay for testing be less than 2 seconds? If that makes sense for your tests, I think it could be good to shorten this so we don't slow our test suite down over time if a lot of things wind up calling delay.

Excellent work, please make the change to the challenge-button.test.tsx file, fetch and merge the latest changes from the upstream repo so your branch is up-to-date, and we'll get this merged.

**Review by dvorakjt — APPROVED** [review]
Approved, thank you!

**Pull request merged**
