### PR TITLE
JIRA-CHAL-28 #done Create a class that can encrypt and decrypt data

### PR DESCRIPTION
**Pull request by IshanBhatBhardwaj**
## Overview

Created a class that can encrypt and decrypt data. Will be used for storing user information on cookies. 

## Test Plan

Created unit tests as well as a small next project that was deplyoed on vercel. All tests passed. 

## Follow ups

I chose the AES-GCM algorithm to encrypt and decrypt data. I believe this is a good choice, but if there are better ones we should switch to those.

### CODE REVIEW

**Review by dvorakjt — CHANGES_REQUESTED** [review]
Hi Ishan,

Thank you for this! Very nice work on this so far! There are some changes I need to request. First some nits:

- Please review the style guide for this project (STYLE_GUIDE.md). This guide exists to keep our code styles uniform across the project. In this document, note that file and directory names should be in kebab case (all lowercase characters with hyphens). Please update your file and directory names to conform to this convention.
- Please remove firestore.debug.log. This was generated when you ran the older version of the project but it should be removed as we are no longer using Firebase.
- In a number of places, you refer to a Uint8Array as "Unit8Array". This should be changed to Uint8 (Uint = unsigned integer).
- Please feel free to import your class like this `'@/services/server/encryption/DataEncryptor'` in your tests. `@/` is an alias for `src/`.
- Nice job using TSDoc comments to describe your class! I would create separate TSDoc comments for each method and place them above the method rather than applying them all at the class level. The developer will get friendlier messages from their code editor and it will keep the code and its description closer together.

Next, some things related to name selection/clarity:
- Class and interface names can be clearer. Below are some suggestions:
	- Directory: "src/services/server/encryption" --> "src/services/server/encryptor" (to match the name of your interface)
	- File: "src/services/server/encryption/interface.ts" --> "src/services/server/encryptor/encryptor.ts" (encryptor is a more descriptive name than interface. Also, it will match the name of the interface declared inside the file)
	- Interface: `DataEncryptorClassMethods` (originally declared in "src/services/server/encryption/interface.ts") --> `Encryptor` (simpler and communicates what classes implementing this interface will do)
	- File: "src/services/server/encryption/DataEncryptor.ts" --> "src/servcies/server/encryptor/web-crypto-subtle-encryptor.ts" (conforms to style guide and describes what this implementation of this Encryptor does)
	- Class: `DataEncryptor` (originally declared in "src/services/server/encryption/DataEncryptor.ts") --> `WebCryptoSubtleEncryptor` (describes the implementation of the interface, which can give developers clues about the context in which it can be used)
- Try to follow the single-responsibility principle, even in your tests. In a perfect world, each test tests one thing. So for instance, your second test is testing two different conditions. When you notice this, break the test down into separate tests.
- Descriptions of what the tests are testing can be clearer (and more grammatically correct). Usually I write my tests like this: `it('performs some action under these conditions.', () => { /* test code */ });` So, looking at the second of your tests as an example, I would break it down into two tests, and clarify their descriptions. One might be `it('throws an error when no key is provided.')` and the other would be `it('throws an error when it attempts to encrypt an empty string')`.

Finally, a few notes about design choices:
- There should be no need to set `this.key`. The decrypt method should also accept a key as a parameter, and the developer utilizing your class should simply pass the same key into both the encrypt and decrypt methods.
- You may not need to check for a falsy key. Since this is TypeScript and you declared the type of the parameter, that should be enough, unless the type you declared is a union that includes null or undefined. Similarly, I don't think there is the need to cast the key as a `CryptoKey` after it has already been received by the function, or redeclare a variable called `cryptoKey` at all, for that matter.
- Is there actually a need to throw an error if it receives an empty string (would the encryption algorithm fail to encrypt it for some reason)? I could envision a scenario in which we have a database table whose fields must all be encrypted, but some of which could be optional. In this case, throwing an error when attempting to encrypt an empty string might be undesirable. 

Thanks in advance for making these changes!

**Comment by dvorakjt** [comment]
Hi Ishan,

Thanks for these changes, it's looking much better. There are a few more things to point out:

- I don't think you need to set an internal boolean flag to indicate that encryption has occurred. The way the DI library works (and many similar libraries work), the class is registered as transient, meaning a new instance is retrieved each time. Additionally, with the way middleware is deployed (I believe it's basically just AWS lambda functions under the hood), state could not be counted on to persist anyway. Instead, other classes dependent on this class will decide what data needs to be encrypted. They will then decrypt that data when it is retrieved. This class doesn't need to make those kinds of decisions. If it receives data to decrypt, it should try to do so, unless the data can be immediately recognized as unencrypted. By this reasoning, your check of the length of the data to decrypt is a good one, but setting and checking a boolean flag is not necessary.
- When you rename a file, make sure to rename the corresponding test, as well as the string passed as the first argument to the corresponding describe block
- I think name given to the class wrapped by `inject` should match the name given to the constant to be assigned the result of the injection (so in this case `WebCryptoSubtleEncryptor`)
- I think the methods can just be called encrypt and decrypt, it's pretty much a given that we'll be encrypting data
- Please remove the vertical space that separates your TSDoc comments from your class declarations and method signatures. You will see in the examples that there is no whitespace separating comments from code (https://tsdoc.org/pages/tags/example/) and if we think about this, it makes sense--we want to associate these comments with the code and the extra line of whitespace has the opposite effect

Thanks again!

**Comment by IshanBhatBhardwaj** [comment]
Thank your for all the great feedback. I made some more changes as requested! I do have a quick question. Now that I no longer have a method to check if a user encrypted data before decryption, would it be good practice to wrap the await crypto.subtle.decrypt() function call in a try catch block? The reason for this is because I wrote a test and if a typical string like "testemail@123" is passed into the decrypt method, an error is thrown from the web crypto API.

**Comment by dvorakjt** [comment]
That's a good question. I think you probably want it to throw an error if decryption fails, which the caller should handle. If you want to throw a custom error, you could wrap it in a try...catch block and throw it from there. I think you could also possibly indicate that it can throw in the TSDoc comment.

**Review by dvorakjt — APPROVED** [review]
Great job, approved!

**Pull request merged**
