### PR TITLE
JIRA-CHAL-17 #DONE Implement Selenium tests in Python for /home  #17

### PR DESCRIPTION
**Pull request by Ris345**
## Description
This PR introduces a comprehensive suite of Selenium tests for the 8by8 Next.js application. The tests cover various functionalities and elements of the application's homepage and multiple sections, ensuring that all key components are rendered correctly and behave as expected. The tests are structured to verify the correct display and interaction of elements, including images, buttons, text, and links. Below is a detailed overview of the tests included in this PR:

## Tests Included
- **General Tests:** Verifies homepage title, logo render, h1 element, and challenge button.
- **Header Tests:** Verifies Hamburger Menu is rendered and the ul, li and button are displayed.
- **Section 1 Tests:** Checks rendering, link navigation, and image display.
- **Section 2 Tests:** Confirms rendering and display of main and secondary images.
- **Section 3 Tests:** Verifies rendering, text content, and image display.
- **Section 4 Tests:** Confirms correct rendering and text content.
- **Section 5 Tests:** Checks rendering, text content, and image display.
- **Section 6 Tests:** Verifies rendering, text content, div content, and image display.
- **Section 7 Tests:** Confirms rendering, text content, button action, and anchor tag.

Screen Shot 2024-08-04 at 12 19 29 AM

### Steps to Verify:
1. **Run the Test Suite:**
   -  To run the Selenium tests, navigate into `src/__tests__/e2e` and run
      `python -m pytest`.
   - Ensure all tests pass without errors.

2. **Make sure the nextJs server is running locally:**
   - Launch the app locally with `npm run dev` or `yarn dev`.
   - Manually check each section and component as per the tests.

## Follow ups

I want to make sure that I have covered all the unit tests on the homepage.

### CODE REVIEW

**Review by dvorakjt — CHANGES_REQUESTED** [review]
Hi Rishav,

This is great. I followed the instructions in the README and all the tests pass. The code is well-organized and well-documented. There are a few small changes to request:

- Let's create a section in the .gitignore for python-specific files (simply add `# python`  to indicate to developers that the ignored files relate to python code and then add ignored folders below)
- `venv`, `__pycache__` and `.pytest_cache` should be added to the gitignore
- Is the myenv file necessary? Could it just be removed altogether rather than gitignored? 
- Please add instructions for activating the venv on Linux
- The test should be called "homepage_test.py" not "hompage_test.py"
- Should developers build and run the compiled project for these tests rather than running the dev server? If so, the instructions in the README should be updated. (I think the answer is yes to avoid timeouts due to page compilation and because these tests are intended to be run against the deployed app anyway)

EDIT: 2 other small things I noticed:
- There are a few unused imports in the test file. Be sure to only import the packages you need
- Could you please add a few notes to the style guide for python (maybe just indicate that we should use snake_case for variables, functions and methods and that we should use docstring for to comment/document code)? This would be super helpful

That's pretty much it, other than that, looks good to go!

**Comment by Ris345** [comment]
Hey, thanks for the review appreciate it! I will work on that today. It looks like  venv is actually myenv but after looking at it __pycache__ and .pytest_cache are all inside that, not sure  just adding myenv to gitignore would do the job?  But let me know, also I will update the readme accordingly with the linux venv environment and add the option for npm build to run the tests instead of npm run dev.

**Comment by dvorakjt** [comment]
Hi Rishav,

Great! In the readme, please make sure to add `npm run start` after `npm run build` to ensure that the production server is started. 

What I meant about the `myenv` file was that when I ran the commands as specified in the updates to the readme, this folder was not created. Instead `venv` was created in the root directory. I'm basically wondering how `myenv` was created. If it's an vestige of a workflow you were trying out before, I think it would be better to remove it entirely, follow the steps in the readme, and then .gitignore only the files created by following those steps. 

Thank you for your hard work!

**Comment by Ris345** [comment]
I added all the required information to the README, removed unused imports, and updated some variable names. To solve this issue, I recreated the virtual environment file in the clone of the Selenium Next.js example. If you cd into the directory, you'll see the content inside venv and myenv is the same. Both these commands create virtual environment they are just different dir names.   `python -m venv venv`  &   `python -m venv myenv`. So then I can add myenv to gitignore along with others.

**Comment by dvorakjt** [comment]
Right, I gotcha. What I'm trying to say (or perhaps failing to say haha!) is that I'd prefer that only the directories created by the commands in the readme are referenced in the gitignore, and that any superfluous directories are removed and replaced with exactly the output of following the instructions in the readme to the letter. Is it possible for you to delete myenv and replace it with exactly the output of the instructions added to the readme? In general, I'd like everyone to be as much on the same page as possible, and little things like this can add up over time to create confusion. Further, when I ran the pytest command, the cache directories were created directly inside the e2e folder, not inside the venv folder as I think you indicated in a previous comment, so I think it's necessary to also add these to the gitignore. Does that make sense?

**Comment by Ris345** [comment]
Yes that makes sense. Thanks for the clarification.

**Comment by dvorakjt** [comment]
Great! Let me know when it's all ready and I'll have another look at it! Thank you!

**Comment by Ris345** [comment]
Hey, I changed all the requested files and committed the changes. The only follow up I have is regarding the style.md maybe if you could take a look and tell me if that is good to go. Also the linux venv enviornment is similar to the macOS venv,  so let  me know if that passes as well.

**Comment by dvorakjt** [comment]
Great! The Python style notes are pretty much exactly what I had in mind.

There are two small issues with the Linux commands:
- The user may have to use the `python3` command instead of `python` depending on how they have Python installed. I think a note should be made of this.
- The command to activate the venv should be `source venv/bin/activate` not `source myenv/bin/activate`

That's everything I can see, good job!

**Comment by Ris345** [comment]
Its done, thanks appreciate it!

**Comment by dvorakjt** [comment]
Very close! You should note that the command _might_ _be_ python3 (from what I understand, some Linux distros use this command for python 3. I verified that this is the case at least in the version of Ubuntu I'm running in WSL. But in other environments, the command is likely just python).

**Comment by Ris345** [comment]
I added some notes to the readme regarding the python & python3 command depending on the environment and OS, let me know if this is relevant?

**Review by dvorakjt — APPROVED** [review]
Approved!

**Pull request merged**
